# Generated by Django 4.1.13 on 2024-10-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grasshopper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlet',
            name='region',
            field=models.CharField(max_length=250, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='athlet',
            name='team',
            field=models.CharField(max_length=250, verbose_name='Название команды'),
        ),
    ]
