# Generated by Django 4.1.13 on 2024-11-07 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grasshopper', '0006_athlet_average_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
