# Generated by Django 4.1.13 on 2025-04-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grasshopper', '0008_athlet_total_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlet',
            name='gender',
            field=models.CharField(choices=[('MN', 'Мужчина'), ('WN', 'Женщина')], max_length=2, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='athlet',
            name='rank',
            field=models.CharField(choices=[('FR', '1 разряд'), ('KM', 'КМС'), ('MS', 'МС'), ('MK', 'МСМК')], default='FR', max_length=2, verbose_name='Разряд'),
        ),
        migrations.AlterField(
            model_name='athlet',
            name='total_result',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
